version: "3.8"

services:
  web:
    build: .
    container_name: libreria-web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - libreria-net

  db:
    image: mysql:8
    container_name: libreria-db
    restart: always
    environment:
      MYSQL_DATABASE: libreria
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - libreria-net

volumes:
  db_data:

networks:
  libreria-net:
    driver: bridge
