version: '3.8'


services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - red_libreria

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libreria
      volumes:
      - ./libreria.sql:/docker-entrypoint-initdb.d/libreria.sql
    ports:
      - "3307:3306"  # Usaste 3307 porque el 3306 estaba ocupado
    networks:
      - red_libreria

networks:
  red_libreria:
    driver: bridge
