version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: libreria_web
    ports:
      - "8080:80"
    volumes:
      - ./libreria:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: libreria_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libreria
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./libreria.sql:/docker-entrypoint-initdb.d/libreria.sql

volumes:
  db_data:
